# Generated by Django 4.1.7 on 2023-03-23 01:23

import Tarea.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=250, verbose_name='Nombre')),
                ('codigo', models.CharField(default='', max_length=30, verbose_name='Codigo')),
                ('modulo', models.BooleanField(default=False, verbose_name='Modulos')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=250, verbose_name='Nombre de la curso')),
                ('paralelo', models.CharField(default='', max_length=250, verbose_name='Paralelo')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('cerrado', models.BooleanField(default=False, verbose_name='Cerrado')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CursoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('cerrada', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.asignatura', verbose_name='Asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.curso', verbose_name='Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(default='', max_length=5000, verbose_name='Descripción')),
                ('enlace', models.CharField(default='', max_length=5000, verbose_name='Enlace')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Recursos', verbose_name='Archivo')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=100, verbose_name='Título')),
                ('description', models.CharField(default='', max_length=5000, verbose_name='Descripción')),
                ('important', models.BooleanField(default=False)),
                ('archivo_qr', models.ImageField(blank=True, null=True, upload_to='Codigo_QR', verbose_name='Código_QR')),
                ('enlace_qr', models.CharField(default='', max_length=800, verbose_name='Enlace de alojamiento')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Archivo_Doc', verbose_name='Documento de tarea')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.cursoasignatura', verbose_name='Asignatura a la que pertenece la tarea')),
                ('recursos', models.ManyToManyField(to='tareas.recurso', verbose_name='Recursos de tarea')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Nombres')),
                ('apellido1', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Primer apellido')),
                ('apellido2', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Segundo apellido')),
                ('cedula', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), Tarea.validators.vcedula])),
                ('genero', models.IntegerField(choices=[(0, '---------'), (1, 'Masculino'), (2, 'Femenino')], default=0, verbose_name='Genero')),
                ('perfil', models.IntegerField(choices=[(0, '----------'), (1, 'Estudiante'), (2, 'Docente'), (3, 'Administrativo')], default=0, verbose_name='Tipo de usuario')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10), Tarea.validators.SoloNumeros], verbose_name='Número de telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección de domicilio')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('correo', models.CharField(default='', max_length=200, verbose_name='Correo electronico')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='Fotos', verbose_name='Foto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cursoasignatura',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.persona', verbose_name='Profesor'),
        ),
        migrations.AddField(
            model_name='cursoasignatura',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursoasignatura',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(related_name='+', to='tareas.persona', verbose_name='Estudiantes inscritos en el curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccesoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('tipoacceso', models.IntegerField(choices=[(1, 'Código QR'), (2, 'Sistema')], default=0, verbose_name='Genero')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.persona', verbose_name='Estudiante que accede')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.task', verbose_name='Tarea')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='cursoasignatura',
            unique_together={('curso', 'asignatura')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre',)},
        ),
    ]
