# Generated by Django 4.1.5 on 2023-03-04 12:28

import Tarea.funciones
import Tarea.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0003_asignatura_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la carrera')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('cupo', models.IntegerField(default=0, verbose_name='Cupo')),
                ('cerrado', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['nombre'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(default='', max_length=30, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='creditos',
            field=models.IntegerField(default=0, verbose_name='Creditos'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='modulo',
            field=models.BooleanField(default=False, verbose_name='Modulos'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(default='', max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=5000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together={('nombre',)},
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(default='', max_length=5000, verbose_name='Descripción')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='Recursos', verbose_name='Archivo')),
                ('enlace', models.CharField(default='', max_length=5000, verbose_name='Enlace')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('apellido1', models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('apellido2', models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(4)])),
                ('cedula', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10), Tarea.validators.vcedula])),
                ('genero', models.IntegerField(choices=[(0, '---------'), (1, 'Masculino'), (2, 'Femenino')], default=0, verbose_name='Genero de la persona')),
                ('perfil', models.IntegerField(choices=[(0, '----------'), (1, 'Estudiante'), (2, 'Docente'), (3, 'Administrativo')], default=0, verbose_name='Perfil de usuario asignado')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(10), Tarea.validators.SoloNumeros])),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Tarea.funciones.Ruta)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarreraAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('cerrada', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.asignatura', verbose_name='Asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.carrera', verbose_name='Carrera')),
                ('estudiantes', models.ManyToManyField(related_name='+', to='tareas.persona', verbose_name='Estudiantes inscritos en la asignatura')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.persona', verbose_name='Profesor')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('carrera', 'asignatura')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.carreraasignatura', verbose_name='Asignatura a la que pertenece la tarea'),
        ),
        migrations.AddField(
            model_name='task',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.persona'),
        ),
        migrations.AddField(
            model_name='task',
            name='recursos',
            field=models.ManyToManyField(to='tareas.recurso', verbose_name='Recursos de tarea'),
        ),
    ]
