# Generated by Django 4.1.5 on 2023-03-04 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0004_carrera_alter_asignatura_options_remove_task_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(default='', max_length=250, verbose_name='Nombre de la curso')),
                ('paralelo', models.CharField(default='', max_length=250, verbose_name='Paralelo')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('cupo', models.IntegerField(default=0, verbose_name='Cupo')),
                ('cerrado', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
        ),
        migrations.CreateModel(
            name='CursoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('cerrada', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.asignatura', verbose_name='Asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.curso', verbose_name='Curso')),
                ('estudiantes', models.ManyToManyField(related_name='+', to='tareas.persona', verbose_name='Estudiantes inscritos en la asignatura')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.persona', verbose_name='Profesor')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('curso', 'asignatura')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='carreraasignatura',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='carreraasignatura',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='carreraasignatura',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='carreraasignatura',
            name='estudiantes',
        ),
        migrations.RemoveField(
            model_name='carreraasignatura',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='carreraasignatura',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='carreraasignatura',
            name='usuario_modificacion',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.AlterField(
            model_name='task',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.cursoasignatura', verbose_name='Asignatura a la que pertenece la tarea'),
        ),
        migrations.DeleteModel(
            name='CarreraAsignatura',
        ),
    ]
