# Generated by Django 4.1.5 on 2023-03-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_curso_cursoasignatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='creditos',
        ),
    ]
